### PR TITLE
Php 8.2.3 Update

### PR DESCRIPTION
**Pull request by caferyukseloglu**
Please release new version if suits you

### CODE REVIEW

**Comment by c9s** [comment]
why close?

**Comment by caferyukseloglu** [comment]
Uh, PHP 7 and more brakes preg_match, it changes '/' with '#', and I am not sure v2 is stable, if it is, I will re update without breaking preg_match.

**Comment by c9s** [comment]
i think it's stable, let's change and test it?

**Comment by caferyukseloglu** [comment]
Okey

**Pull request closed without merging**
